<?php

/**
 * Implements hook_menu().
 */
function galaxy_tool_generator_ui_menu() {
  $items['galaxy_tool_xml'] = [
    'title' => 'Galaxy Tool XML',
    'description' => t('A page to view Galaxy tool XML'),
    'page callback' => 'drupal_get_form',
    'page callback' => 'page_test',
    'page arguments' => ['galaxy_tool_xml_form'],
    'access arguments' => ['access content'],
    'menu_name' => 'main-menu',
    'type' => MENU_NORMAL_ITEM,
    'file' => 'includes/galaxy_tool_xml.form.inc',
    'weight' => 2,
  ];

  return $items;
}
